// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import NavbarController from "./navbar_controller"
import RemovalsController from "./removals_controller"

application.register("removals", RemovalsController)
application.register("navbar", NavbarController)
